numberCatValues = [
    '0_0' ,
    '1_0' ,
    '1_1' ,
    '1_2' ,
    '1_3' ,
    '2_0' ,
    '2_1' ,
    '3_0' ,
    '3_1' ,
    '3_2' ,
    '4_0' ,
    '4_1' ,
    '4_2' ,
    '4_3' ,
    '5_0' ,
    '5_1' ,
    '6_0' ,
    '6_1']
stringCatValues = [
    'All' ,
    'Anime' ,
    'Anime Music Video' ,
    'Anime - English-translated' ,
    'Anime - Non-English-translated' ,
    'Anime - Raw' ,
    'Audio' ,
    'Lossless' ,
    'Lossy' ,
    'Literature' ,
    'Literature - English-translated' ,
    'Literature - Non-English-translated' ,
    'Literature - Raw' ,
    'Live Action' ,
    'Live Action - English-translated' ,
    'Idol/Promotional Video' ,
    'Live Action - Non-English-translated' ,
    'Live Action - Raw' ,
    'Pictures' ,
    'Graphics' ,
    'Photos' ,
    'Software' ,
    'Applications' ,
    'Games']
argStringValues = ["term","category","filter","page","sortType","sortDirection","user"]
argValues = ["q","c","f","p","s","o","u"]
module.exports = { numberCatValues, stringCatValues, argStringValues, argValues }